### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by bbougot** [ArmandGrillet/Adios#6]
Very promising project, congrat @ArmandGrillet 
Would it be possible to add a Gitter.im to the README.md, so that it would be easier to talk about it ?

Also, is this app currently released on the App Store ? It would be nice to offer a free alternative to Peace/Crystal/Purify.

Nice job anyway !

**Comment by vaevictis** [comment]
Would be keen on helping out maintaining an open-source ad-blocker :)
@bbougot I don't think it is on the App Store, @ArmandGrillet made an announcement that he was abandoning the project to release it if I got [macg](http://www.igen.fr/app-store/2015/09/adios-dit-adieu-au-secteur-pourri-des-bloqueurs-de-pub-pour-ios-9-93020) article right.

**Comment by ArmandGrillet** [comment]
I was more thinking of Adios to be a base for new ad blockers as the app won't be on the App Store. If you want to create something from it I encourage you to fork it and start something new going in the direction you like!

**Comment by bbougot** [comment]
I've read the macg article. That makes sense, it's a a fuzzy and wild market... Anywayt, much respect for what you've done :+1: 

Chapeau !

**Comment by vaevictis** [comment]
Agreed. _Sacré boulot_!
@bbougot interested in trying to build an opensource adblocker for iOS? :D

**Comment by bbougot** [comment]
Absolutely! Time to get rid off all these annoying ads. It still misses a -free- good ad blocker.

**Comment by ArmandGrillet** [comment]
The `README.md` has been updated with the Gitter badge and more details concerning the two branches!

**Comment by bbougot** [comment]
Thanks @ArmandGrillet !
I'm closing this issue
