### ISSUE TITLE
This application is modifying the autolayout engine from a background thread

### ISSUE THREAD

**Issue by vaevictis** [ArmandGrillet/Adios#8]
So, I forked Adios tonight (I'm in Australia), and tried to get it to run locally.

I got through the few compile errors and warnings (signature issues, external framework dependencies missing, forced unwrapping of an optional which happens to sometimes be nil...). I now can launch Adios either on a simulator or on my iPad running iOS 9.
But.
Just after the filters list download (that I can witness in the console window of xcode), I get this message:
```This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.```

I'm trying to understand the Storyboard at the moment to find out where's the transition between updating lists and _displaying whatever comes next_ happens.

It seems to be a common iOS error. Some googling around suggests that the code modifying the autolayout should simply by executed in the main queue.

Anyway, I'm not sure to totally understand the issue here, but if I could just get a suggestion as to where to start debugging for layout alterations once the lists are downloaded, it would be ace.

**Comment by ArmandGrillet** [comment]
I suggest you to check the methods of the View Controller `LoadingVewController`, they're running some method in the model to download and apply the lists in a background thread.

**Comment by ArmandGrillet** [comment]
There is a problem with the `UpdateViewController`, let me find the bug...

**Comment by armandgrillet** [comment]
The problem has been solved, it was an issue in the method `updateNotification` of `UpdateViewController` performing a segue in a background thread.

**Comment by vaevictis** [comment]
Great!

**Comment by matacao** [comment]
Bonsoir,

I have also the same problem with an iPhone 6S on ios 9.2 and I didn't find a solution.
Anyone have an idea ?

Thanks.
