### ISSUE TITLE
app is not available on Appstore

### ISSUE THREAD

**Issue by amosavian** [ArmandGrillet/Adios#9]
Hi,
when can i find this great app on App Store?

**Comment by armandgrillet** [comment]
Adios won't be available directly on the App Store. Forks of this project can be though.

**Comment by amosavian** [comment]
is there any specific reason?

**Comment by armandgrillet** [comment]
Yes, [here is the English traduction of the article explaining why](https://translate.google.fr/translate?sl=fr&tl=en&js=y&prev=_t&hl=fr&ie=UTF-8&u=http%3A%2F%2Fwww.igen.fr%2Fapp-store%2F2015%2F09%2Fadios-dit-adieu-au-secteur-pourri-des-bloqueurs-de-pub-pour-ios-9-93020&edit-text=&act=url).

**Comment by ghost** [comment]
Do you know of any fork that released an app on the App Store? I'm happy to pay for it if needed.

**Comment by armandgrillet** [comment]
@Rjevski Not that I know of, I personally use [Firefox Focus](https://itunes.apple.com/us/app/firefox-focus-privacy-browser/id1055677337?mt=8). If you want to help the Mozilla Foundation which is behind this app, you can make a donation [here](https://donate.mozilla.org).
